; Copyright © Microsoft Corp.

[Theme]
; Windows - IDS_THEME_DISPLAYNAME_Windows X
DisplayName=Windows X
SetLogonBackground=0

[Control Panel\Desktop]
Wallpaper=%SystemRoot%\Resources\Themes\Windows X\Windows X.jpg
TileWallpaper=0
WallpaperStyle=10
Pattern=

[VisualStyles]
Path=%SystemRoot%\Resources\Themes\Windows X\Windows X.msstyles
ColorStyle=NormalColor
Size=NormalSize
ColorizationColor=0XFFD9D9D9

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS